repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  # Linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]

  # Run tests with coverage check
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest with coverage
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          "--cov=src",
          "--cov-report=term-missing",
          "--cov-fail-under=70",
          "-v"
        ]
